# Generated by Django 2.2.3 on 2020-02-09 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='webiste',
            new_name='website',
        ),
    ]
